apiVersion: v1 
kind: Pod
metadata:
  name: ycsb
  namespace: mongodb
#spec:
#  selector:
#    matchLabels:
#      app: mongo
#  template:
#    metadata:
#      labels:
#        app: mongo
spec:
  containers:
  - name: ycsb
    image: jedimt/ycsb:v8
    ports:
    - containerPort: 22
  restartPolicy: Never
